package com.krzywdek19.product_service.model;

public enum Category {
    SHIRTS, SHOES, JACKETS, ELECTRONICS, COMPUTERS, BOOKS, FURNITURE, TOYS, GROCERIES, BEAUTY, SPORTS, AUTOMOTIVE, MUSIC, MOVIES, GARDEN, PETS
}
